#!/bin/sh
# Fix up mount points device node names.
#
# /data needs to be mounted in initrd, but there is no udev that early,
# which means there is no /dev/block/platform/*/by-name/* (or bootdevice).
# This file is a map from the "by-name" path to /dev/mmcblkMpN.
# It also serves dhd to convert fstab and *.rc mount entries to systemd units,
# because at that boot stage there is still no udev "by-name" paths, even when
# systemd starts to execut the "*.mount" units.

DEVICE=$1
shift

echo "Fixing mount-points for device $DEVICE"

case "$DEVICE" in
    "matisse" | "matissewifi" | "matisse3g" | "matisselte")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p23 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p26 ' \
            -e 's block/platform/msm_sdcc.1/by-name/recovery mmcblk0p15 ' \
            -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p21 ' \
            -e 's block/platform/msm_sdcc.1/by-name/modem mmcblk0p2 ' \
            -e 's block/platform/msm_sdcc.1/by-name/modemst1 mmcblk0p12 ' \
            -e 's block/platform/msm_sdcc.1/by-name/modemst2 mmcblk0p13 ' \
            -e 's block/platform/msm_sdcc.1/by-name/apnhlos mmcblk0p1 ' \
            -e 's block/platform/msm_sdcc.1/by-name/efs mmcblk0p11 ' \
            -e 's block/platform/msm_sdcc.1/by-name/cache mmcblk0p24 ' \
            -e 's block/platform/msm_sdcc.1/by-name/boot mmcblk0p14 ' \
            "$@"
        ;;

    "i9305" | "encore" | "n7000" | "n7100" | "i9300" | "anzu" | \
    "coconut" | "haida" | "hallon" | "iyokan" | "mango" | "phoenix" | \
    "satsuma" | "smultron" | "urushi" | "zeus" | "jenad")
    # Untested for other revisions of Samsung GT-S6500:
    # | "jena" | "trebon")
        sed -i \
            -e 's /block/ / ' \
            "$@"
        ;;

    "p3100" | "p3110" | "p3113" | "p5100" | "p5110" | "p5113" | "espressowifi" | "espresso3g" | "i9100g")
        sed -i \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/DATAFS mmcblk0p10 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/KERNEL mmcblk0p5 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/FACTORYFS mmcblk0p9 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/EFS mmcblk0p1 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/CACHE mmcblk0p7 ' \
            "$@"
        ;;

    "gts210ltexx"|"gts210wifi")
        sed -i \
            -e 's block/platform/15540000.dwmmc0/by-name/BOOT mmcblk0p9 ' \
            -e 's block/platform/15540000.dwmmc0/by-name/CACHE mmcblk0p20 ' \
            -e 's block/platform/15540000.dwmmc0/by-name/EFS mmcblk0p3 ' \
            -e 's block/platform/15540000.dwmmc0/by-name/SYSTEM mmcblk0p19 ' \
            -e 's block/platform/15540000.dwmmc0/by-name/USERDATA mmcblk0p22 ' \
            "$@"
        ;;

    "beyond2lte")
        sed -i \
            -e 's block/platform/13d60000.ufs/by-name boot sda14 ' \
            -e 's block/platform/13d60000.ufs/by-name bota0 sda1 ' \
            -e 's block/platform/13d60000.ufs/by-name bota1 sda2 ' \
            -e 's block/platform/13d60000.ufs/by-name bota2 sda8 ' \
            -e 's block/platform/13d60000.ufs/by-name bota3 sda24 ' \
            -e 's block/platform/13d60000.ufs/by-name cache sda28 ' \
            -e 's block/platform/13d60000.ufs/by-name cp_debug sda30 ' \
            -e 's block/platform/13d60000.ufs/by-name cpefs sdd1 ' \
            -e 's block/platform/13d60000.ufs/by-name dqmdbg sda22 ' \
            -e 's block/platform/13d60000.ufs/by-name dtb sda12 ' \
            -e 's block/platform/13d60000.ufs/by-name dtbo sda13 ' \
            -e 's block/platform/13d60000.ufs/by-name efs sda3 ' \
            -e 's block/platform/13d60000.ufs/by-name keydata sda21 ' \
            -e 's block/platform/13d60000.ufs/by-name keyrefuge sda20 ' \
            -e 's block/platform/13d60000.ufs/by-name keystorage sda6 ' \
            -e 's block/platform/13d60000.ufs/by-name misc sda19 ' \
            -e 's block/platform/13d60000.ufs/by-name nad_refer sda17 ' \
            -e 's block/platform/13d60000.ufs/by-name omr sda29 ' \
            -e 's block/platform/13d60000.ufs/by-name param sda4 ' \
            -e 's block/platform/13d60000.ufs/by-name persistent sda18 ' \
            -e 's block/platform/13d60000.ufs/by-name product sda27 ' \
            -e 's block/platform/13d60000.ufs/by-name radio sda16 ' \
            -e 's block/platform/13d60000.ufs/by-name recovery sda15 ' \
            -e 's block/platform/13d60000.ufs/by-name sec_efs sda7 ' \
            -e 's block/platform/13d60000.ufs/by-name steady sda9 ' \
            -e 's block/platform/13d60000.ufs/by-name system sda25 ' \
            -e 's block/platform/13d60000.ufs/by-name uh sda10 ' \
            -e 's block/platform/13d60000.ufs/by-name uhcfg sda11 ' \
            -e 's block/platform/13d60000.ufs/by-name up_param sda5 ' \
            -e 's block/platform/13d60000.ufs/by-name userdata sda31 ' \
            -e 's block/platform/13d60000.ufs/by-name vbmeta sda23 ' \
            -e 's block/platform/13d60000.ufs/by-name vendor sda26 ' \
            "$@"
        ;;
    *)
        cat <<EOF

****************************************************************
****************************************************************
ERROR: $DEVICE does not have mountpoint fixup data - see
       Sailfish OS HADK for details on how to fix this.
****************************************************************
****************************************************************

EOF
        exit 1
        ;;
esac

